# Automatic node configuration has only been tested on GKE.
{{ if (.Capabilities.KubeVersion.GitVersion | regexMatch "gke") }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pso-node-config
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      name: pso-node-config
  template:
    metadata:
      labels:
        name: pso-node-config
    spec:
      hostPID: true
      containers:
      - name: pso-node-config
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c", "/node-configure.sh"]
        securityContext:
          privileged: true
{{ end }}
